# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: php-pv-1
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /tmp/data/pv-1
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-2
